---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-vol
  labels: 
    name: my-vol
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce