---
apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmap
  labels:
    app: dov-bear-cm
data:
  INSTANCE_NAME: dov-bear-instance-name

---
apiVersion: v1
kind: Secret
metadata:
  name: dov-bear-secret
  labels:
    name: dov-bear-secret
type: Opaque
data:
  INSTANCE_NAME: aGVsbG9vbw==
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: dov-bear-deploy 
  labels:
    name: dov-bear-deploy
spec:
  replicas: 4
  selector: 
    matchLabels:
      name: dov-bear-po
  template: 
    metadata:
      name: dov-bear-po
      labels:
        name: dov-bear-po
        dept: eng
    spec:
      containers:
      - image:  chukmunnlee/dov-bear:v2
        imagePullPolicy: IfNotPresent
        name:  dov-bear-container
        ports:
        - name: dov-port
          containerPort: 3000
        envFrom:
        - secretRef:
            name: dov-bear-secret
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
            scheme: HTTP

---
apiVersion: v1
kind: Service
metadata:
  name: dov-bear-svc
  labels: 
    name: dov-bear-svc
spec:
  type: LoadBalancer
  selector:
    name: dov-bear-po
  ports:
  - port: 80
    targetPort: dov-port
